version: 1
formatters:
  detailed:
    class: logging.Formatter
    format: '%(asctime)s: %(levelname)-8s: %(name)-24s: %(process)-5d: %(funcName)-24s: %(message)s'
  simple:
    class: logging.Formatter
    format: '%(levelname)-8s: %(name)-24s: %(process)-5d: %(funcName)-24s: %(message)s'
handlers: 
  console:
    class: logging.StreamHandler
    formatter: simple
    level: INFO
  file:
    class: logging.FileHandler
    filename: log/worker.log
    mode: w
    formatter: detailed
  errors:
    class: logging.FileHandler
    filename: log/worker-errors.log
    mode: w
    formatter: detailed
    level: ERROR
root: 
  handlers: [console, file, errors]
  level: DEBUG
        