# You have to download Librispeech "online nnet2" models in order to use this sample
# Run download-librispeech-nnet2.sh in 'test/models' to download them.
use-nnet: True
decoder:
    # All the properties nested here correspond to the kaldinnet2onlinedecoder GStreamer plugin properties.
    # Use gst-inspect-1.0 ./libgstkaldionline2.so kaldinnet2onlinedecoder to discover the available properties
    use-threaded-decoder: true
    model : data/models/english/librispeech_nnet_a_online/final.mdl
    word-syms : data/models/english/librispeech_nnet_a_online/words.txt
    fst : data/models/english/librispeech_nnet_a_online/HCLG.fst
    mfcc-config : data/models/english/librispeech_nnet_a_online/conf/mfcc.conf
    ivector-extraction-config : data/models/english/librispeech_nnet_a_online/conf/ivector_extractor.fixed.conf
    max-active: 10000
    beam: 10.0
    lattice-beam: 6.0
    acoustic-scale: 0.083
    do-endpointing : true
    endpoint-silence-phones : "1:2:3:4:5:6:7:8:9:10"
    traceback-period-in-secs: 0.25
    chunk-length-in-secs: 0.25
    num-nbest: 10
    #Additional functionality that you can play with:
    #lm-fst:  data/models/english/librispeech_nnet_a_online/G.fst
    #big-lm-const-arpa: data/models/english/librispeech_nnet_a_online/G.carpa
    #phone-syms: data/models/english/librispeech_nnet_a_online/phones.txt
    #word-boundary-file: data/models/english/librispeech_nnet_a_online/word_boundary.int
    #do-phone-alignment: true
out-dir: tmp
use-cutter: False
silence-timeout: 10